#!/bin/bash
echo $$ > /var/run/myscript.pid

function finish {
  rm -f /var/run/myscript.pid
  exit 0
}

trap "echo 'I hate the kill command'; exit 0" SIGTERM
trap "echo 'Y U no love me?!'; exit 0" SIGINT
trap finish SIGQUIT SIGTERM

while :
do
  echo "To infinity and beyond"
done
