#!/usr/bin/env bash
# Prints Best School 10 times

start=1
end=20
i=$start

while [[ $i -le $end ]]; do
	echo $i
	case $i in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	((i = i + 1))
done
