#!/usr/bin/env bash
# a script that prints info about the school file

file="school"

if [ -e $file ]; then
	echo "school file exists"
else
	echo "school file does not exist"
	exit
fi
if [ -s $file ]; then
	echo "school file is not empty"
else
	echo "school file is empty"
fi
if [ -f $file ]; then
	echo "school is a regular file"
fi
